# Supabase credentials
SUPABASE_URL = "https://kqrgqemxocmgucpimmqe.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxcmdxZW14b2NtZ3VjcGltbXFlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODIxOTcyOCwiZXhwIjoyMDczNzk1NzI4fQ.kjCYHmY-E7LFdL42qitoGkhH8IAyYfaces-TMzb3MOE"
